variable "ami_id" {}
variable "instance_type" {}
variable "subnet_id" {}
variable "subnet_ids" {}
variable "desired_capacity" {}
variable "max_size" {}
variable "min_size" {}
#variable "user_data" {}
variable "target_group_arn" {}